config/routes.rb
Rails.application.routes.draw do
  resources :candidates, only: [:show, :index]
  root to: 'pages#home'
  get 'compare' => 'candidates#compare', as: 'compare'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :interactions
  has_many :topwords
  has_many :twitterdata
  has_many :words, through: :topwords
end

app/models/interaction.rb
class Interaction < ActiveRecord::Base
  belongs_to :candidate
end

app/models/topword.rb
class Topword < ActiveRecord::Base
  belongs_to :candidate
  has_many :words, dependent: :destroy
end

app/models/twitterdatum.rb
class Twitterdatum < ActiveRecord::Base
  belongs_to :candidate
  validates_uniqueness_of :id_twitter
  # validates :id_twitter, uniqueness: { scope: :candidate_id }

  def decode_data
    ActiveSupport::JSON.decode(ActiveSupport::Gzip.decompress(self.data))
  end

  def encode_data(data)
    ActiveSupport::Gzip.compress(ActiveSupport::JSON.encode(data))
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :topword
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show]

  def index
    redirect_to candidate_path(search_candidate_params['name'].to_i)
  end

  def show
    # navigation arrows
    results = []
    Candidate.all.each do |candidate|
      results << candidate.id
    end
    index = results.find_index(params[:id].to_i)
    results[index + 1].nil? ? @next_id = results.first : @next_id = results[index + 1]
    @previous_id = results[index - 1]

    # TOPWORDS
    # top words in candidates bios
    @topwords_bio = @candidate.topwords.where(data_type: "followers bios").first.words.reverse
    # top mentions in candidate tweets
    @top_candidate_mentions = @candidate.topwords.where(data_type: "mentions").first.words.reverse
    # top mentions in candidate retweets
    @top_rt_mentions = @candidate.topwords.where(data_type: "RT mentions").first.words.reverse
    # top users retweeted by candidate
    @users_retweeted_by_candidate = @candidate.topwords.where(data_type: "candidate retweeted").first.words.reverse
    # top hashtags in candidate tweets
    @hashtags_in_tweets = @candidate.topwords.where(data_type: "hashtags").first.words.reverse
    # Hashtags in candidate retweets
    # @hashtags_in_retweets = @candidate.topwords.where(data_type: "RT hashtags").first.words

    # INTERACTIONS
    # retweets on candidate tweets
    @retweets_on_candidate = @candidate.interactions.where(data_type: "retweets").first
    # favs on candidate tweets
    @favorites_on_candidate = @candidate.interactions.where(data_type: "favorites").first
    # candidate retweets
    @candidate_retweets = @candidate.interactions.where(data_type: "candidate retweets").first
    # followers of candidate's followers
    @followers_followers = @candidate.interactions.where(data_type: "followers followers").first
    # lists that contain the candidate followers
    @lists_containing_followers = @candidate.interactions.where(data_type: "followers listed").first
    # followers tweets
    @followers_tweets = @candidate.interactions.where(data_type: "followers tweets").first
    # followers followings
    @followers_followings = @candidate.interactions.where(data_type: "followers followings").first
  end

  def compare
    @candidates = Candidate.all
    #tableau retweets/favorites
    @data_retweets_favorites = @candidates.map do |c|
      { retweets: c.interactions.where(data_type: "retweets").first.average,
        favorites: c.interactions.where(data_type: "favorites").first.average,
        followers: c.followers_count,
        name: c.name,
        id: c.id
      }
    end

    @data_followers_followers = @candidates.map do |c|
      { followers_tweets: c.interactions.where(data_type: "followers tweets").first.average,
        followers_followers: c.interactions.where(data_type: "followers followers").first.average,
        name: c.name,
        id: c.id
      }
    end

    @data_followers_followings = @candidates.map do |c|
      { followers: c.followers_count,
        followings: c.following_count,
        name: c.name,
        id: c.id
      }
    end
  end

  private
  # find candidate ID before each method
  def set_candidate
    @candidate = Candidate.find(params[:id])
  end

  def search_candidate_params
    params.require(:search).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @candidates = Candidate.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/candidates/compare.html.erb
<div class="container page-padding">
<!--   <div class="header">
    <h1>Compare the candidates</h1>
  </div> -->

  <div class="row">
  <!-- A GAUCHE -->
    <div class="col-xs-12 col-md-3">
      <div class="candidate-menu">
        <div class="candidate-flex">
          <% @candidates.each do |candidate| %>
            <div class="candidate-button">
              <div class="candidate-avatar" id="<%=candidate.screen_name%>" data-target="#<%=candidate.id%>">
                <%= image_tag candidate.picture %>
              </div>
              <div class="candidate-info hidden-xs hidden-sm">
                <div class="candidate-name">
                  <%= candidate.name %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

<!-- GRAPHS -->
    <div class="col-xs-12 col-md-9">
      <div class='chart-menu'>
        <div id='followings-menu' data-chart='followings' class='chart-menu-item active cursor'>Comptes</div>
        <div id='followers-menu' data-chart='followers' class='chart-menu-item cursor'>Communautés</div>
        <div id='favorites-menu' data-chart='favorites' class='chart-menu-item cursor'>Performances</div>
      </div>
      <hr id="filet">
      <p class="legend" id="followings-legend">Comparez le nombre de personnes qui suivent et qui sont suivies par chaque candidat</p>
      <p class="legend hidden" id="followers-legend">Comparez le nombre moyen de followers et de tweets publiés par les abonnés de chaque candidat</p>
      <p class="legend hidden" id="favorites-legend">Comparez le nombre moyen de retweets et de favoris reçus par les tweets de chaque candidat</p>
      <div class="chart-overlay">
        <div class="chart-container" id="followings"></div>
        <div class="chart-container hidden" id="followers"></div>
        <div class="chart-container hidden" id="favorites"></div>
      </div>
    </div>

  </div>
</div>

<!-- CREEPY SCATTER_BOB -->

<% content_for(:after_js) do %>
  <script>

  var margin = {top: 20, right: 20, bottom: 30, left: 40},
      // width = window.innerWidth * 0.6,
      width = $('.chart-container').width() - 60,
      height = 500 - margin.top - margin.bottom;
  /*
   * value accessor - returns the value to encode for a given data object.
   * scale - maps value to a visual display encoding, such as a pixel position.
   * map function - maps from data value to display value
   * axis - sets up axis
   */

  var data = <%= @data_retweets_favorites.to_json.html_safe %>;

  // setup x
  var xValue = function(d) { return d["favorites"];}, // data -> value
      xScale = d3.scale.linear().range([0, width]), // value -> display
      xMap = function(d) { return xScale(xValue(d));}, // data -> display
      xAxis = d3.svg.axis().scale(xScale).orient("bottom");

  // setup y
  var yValue = function(d) { return d["retweets"];}, // data -> value
      yScale = d3.scale.linear().range([height, 0]), // value -> display
      yMap = function(d) { return yScale(yValue(d));}, // data -> display
      yAxis = d3.svg.axis().scale(yScale).orient("left");

  // Setup fill color
  var color = d3.scale.category10();

  // add the graph canvas to the body of the webpage
  var svg = d3.select("#favorites").append("svg")
      .attr("width", width + margin.left + margin.right)
      .attr("height", height + margin.top + margin.bottom)
    .append("g")
      .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  // add the tooltip area to the webpage
  var tooltip = d3.select("body").append("div")
      .attr("class", "tooltip")
      .style("opacity", 0);

  // Don't want dots overlapping axis, so add in buffer to data domain
  xScale.domain([d3.min(data, xValue) - 0.1, d3.max(data, xValue)]);
  yScale.domain([d3.min(data, yValue) - 5, d3.max(data, yValue)]);

  // x-axis
  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis)
    .append("text")
      .attr("class", "label")
      .attr("x", width)
      .attr("y", -6)
      .style("text-anchor", "end")
      .text("Favorites");

  // y-axis
  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("class", "label")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Retweets");

  // draw dots
  svg.selectAll(".dot")
      .data(data)
    .enter().append("circle")
      .attr("class", "dot")
      .attr("r", 12)
      .attr("cx", xMap)
      .attr("cy", yMap)
      .attr("id", function(d) { return d["id"]})
      .style("fill", function(d, i) { return color(i);})
      .on("mouseover", function(d) {
          tooltip.transition()
               .duration(200)
               .style("opacity", .9);
          tooltip.html("<div class='card-candidate text-center'>"
                        + "<h2>" + d["name"] + "</h2>"
                        + "</div>")
               .style("left", (d3.event.pageX - 180) + "px")
               .style("top", (d3.event.pageY - 28) + "px");
      })
      .on("mouseout", function(d) {
          tooltip.transition()
               .duration(500)
               .style("opacity", 0);
      });

  </script>
<% end %>

<% content_for(:after_js) do %>
  <script>

  var margin = {top: 20, right: 20, bottom: 30, left: 40},
      // width = window.innerWidth * 0.6,
      width = $('.chart-container').width() - 60,
      height = 500 - margin.top - margin.bottom;
  /*
   * value accessor - returns the value to encode for a given data object.
   * scale - maps value to a visual display encoding, such as a pixel position.
   * map function - maps from data value to display value
   * axis - sets up axis
   */

  var data = <%= @data_followers_followers.to_json.html_safe %>;

  // setup x
  var xValue = function(d) { return d["followers_tweets"];}, // data -> value
      xScale = d3.scale.linear().range([0, width]), // value -> display
      xMap = function(d) { return xScale(xValue(d));}, // data -> display
      xAxis = d3.svg.axis().scale(xScale).orient("bottom");

  // setup y
  var yValue = function(d) { return d["followers_followers"];}, // data -> value
      yScale = d3.scale.linear().range([height, 0]), // value -> display
      yMap = function(d) { return yScale(yValue(d));}, // data -> display
      yAxis = d3.svg.axis().scale(yScale).orient("left");

  // Setup fill color
  var color = d3.scale.category10();

  // add the graph canvas to the body of the webpage
  var svg = d3.select("#followers").append("svg")
      .attr("width", width + margin.left + margin.right)
      .attr("height", height + margin.top + margin.bottom)
    .append("g")
      .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  // add the tooltip area to the webpage
  var tooltip = d3.select("body").append("div")
      .attr("class", "tooltip")
      .style("opacity", 0);

  // Don't want dots overlapping axis, so add in buffer to data domain
  xScale.domain([d3.min(data, xValue)-400, d3.max(data, xValue)+400]);
  yScale.domain([d3.min(data, yValue)-400, d3.max(data, yValue)+400]);

  // x-axis
  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis)
    .append("text")
      .attr("class", "label")
      .attr("x", width)
      .attr("y", -6)
      .style("text-anchor", "end")
      .text("Tweets");

  // y-axis
  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("class", "label")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Followers");

  // draw dots
  svg.selectAll(".dot")
      .data(data)
    .enter().append("circle")
      .attr("class", "dot")
      .attr("r", 12)
      .attr("cx", xMap)
      .attr("cy", yMap)
      .attr("id", function(d) { return d["id"]})
      .style("fill", function(d, i) { return color(i);})
      .on("mouseover", function(d) {
          tooltip.transition()
               .duration(200)
               .style("opacity", .9);
          tooltip.html("<div class='card-candidate text-center'>"
                        + "<h2>" + d["name"] + "</h2>"
                        + "</div>")
               .style("left", (d3.event.pageX - 180) + "px")
               .style("top", (d3.event.pageY - 28) + "px");
      })
      .on("mouseout", function(d) {
          tooltip.transition()
               .duration(500)
               .style("opacity", 0);
      });

  </script>
<% end %>

<% content_for(:after_js) do %>
  <script>

  var margin = {top: 20, right: 20, bottom: 30, left: 40},
      // width = window.innerWidth * 0.6,
      width = $('.chart-container').width() - 60,
      height = 500 - margin.top - margin.bottom;
  /*
   * value accessor - returns the value to encode for a given data object.
   * scale - maps value to a visual display encoding, such as a pixel position.
   * map function - maps from data value to display value
   * axis - sets up axis
   */

  var data = <%= @data_followers_followings.to_json.html_safe %>;

  // setup x
  var xValue = function(d) { return d["followings"] / 1000 ;}, // data -> value
      xScale = d3.scale.linear().range([0, width]), // value -> display
      xMap = function(d) { return xScale(xValue(d));}, // data -> display
      xAxis = d3.svg.axis().scale(xScale).orient("bottom");

  // setup y
  var yValue = function(d) { return d["followers"] / 1000 ;}, // data -> value
      yScale = d3.scale.linear().range([height, 0]), // value -> display
      yMap = function(d) { return yScale(yValue(d));}, // data -> display
      yAxis = d3.svg.axis().scale(yScale).orient("left");

  // Setup fill color
  var color = d3.scale.category10();

  // add the graph canvas to the body of the webpage
  var svg = d3.select("#followings").append("svg")
      .attr("width", width + margin.left + margin.right)
      .attr("height", height + margin.top + margin.bottom)
    .append("g")
      .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  // add the tooltip area to the webpage
  var tooltip = d3.select("body").append("div")
      .attr("class", "tooltip")
      .style("opacity", 0);

  // Don't want dots overlapping axis, so add in buffer to data domain
  xScale.domain([d3.min(data, xValue) - 0.1, d3.max(data, xValue)]);
  yScale.domain([d3.min(data, yValue) - 5, d3.max(data, yValue)]);

  // x-axis
  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis)
    .append("text")
      .attr("class", "label")
      .attr("x", width)
      .attr("y", -6)
      .style("text-anchor", "end")
      .text("Kilo-Followings");

  // y-axis
  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("class", "label")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Kilo-Followers");

  // draw dots
  svg.selectAll(".dot")
      .data(data)
    .enter().append("circle")
      .attr("class", "dot")
      .attr("r", 12)
      .attr("cx", xMap)
      .attr("cy", yMap)
      .attr("id", function(d) { return d["id"]})
      .style("fill", function(d, i) { return color(i);})
      .on("mouseover", function(d) {
          tooltip.transition()
               .duration(200)
               .style("opacity", .9);
          tooltip.html("<div class='card-candidate text-center'>"
                        + "<h2>" + d["name"] + "</h2>"
                        + "</div>")
               .style("left", (d3.event.pageX - 180) + "px")
               .style("top", (d3.event.pageY - 28) + "px");
      })
      .on("mouseout", function(d) {
          tooltip.transition()
               .duration(500)
               .style("opacity", 0);
      });

  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:400,300,700|Quicksand:400,300,700|Raleway:100,200,300" type='text/css'>
    <title>Impact: Le baromètre Twitter de la politique française.</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<!-- give access to next section "candidates" -->
<div class="home-content home-content-white" id="liste-candidats">
  <div class="link-back link-back-dark text-center">
    <%= link_to root_path << "#accueil" do %>
      <i class="fa fa-angle-up"></i>
    <% end %>
  </div>
  <!-- display all candidates -->
  <div class="container text-center">
    <div class="row">
      <% @candidates.each do |candidate| %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <div class="candidate-card pulsed">
            <%= image_tag candidate.picture, class: "candidate-card"%>
            <%= link_to candidate_path(candidate.id), class: "candidate-card-shadow" do %>
              <h4><%= candidate.name %></h4>
              <h5>@<%= candidate.screen_name %></h5>
              <p><%= candidate.party %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <span id="a-propos"></span>
</div>
<!-- give access to accueil -->
<div class="home-content home-content-blue">
  <div class="link-back link-back-white text-center">
    <%= link_to root_path << "#accueil" do %>
      <i class="fa fa-angle-up"></i>
    <% end %>
  </div>
  <!-- content section "A propos" -->
  <div class="container text-center">
      <div class="row">
        <div class="col-xs-12 col-md-6-offset-6">
          <div class="home-data">
            <h3>Impact décortique les comptes Twitter des candidats aux élections régionales pour vous en offrir une vision claire et synthétique</h3>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="home-data">
            <%= image_tag 'white_pie.png', class:"banner-icon" %>
            <h5>Analysez leurs messages</h5>
            <p>Découvrez ses hashtags favoris, analysez l'impact de son message.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="home-data">
            <%= image_tag 'white_network.png', class:"banner-icon" %>
            <h5>Explorez leurs communautés</h5>
            <p>Qui sont ses followers? Qui diffuse son message?</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="home-data">
            <%= image_tag 'white_bird.png', class:"banner-icon"%>
            <h5>Evaluez leurs performances</h5>
            <p>Mettez vos candidats face à face. Qui maitrise Twitter?</p>
            <br>
            <%= link_to "Comparer les candidats", compare_path, class: "btn btn-danger" %>
          </div>
        </div>
    </div>
  </div>
</div>

<!-- TWITTER FEED -->
<div class="home-content home-content-white" id="feed">
  <div class="title text-center">
    <h2>Les tweets des candidats en direct :</h2>
  </div>
  <!-- give access to accueil -->
  <div class="link-back link-back-dark text-center">
    <%= link_to root_path << "#accueil" do %>
      <i class="fa fa-angle-up"></i>
    <% end %>
  </div>

  <div class="container text-center">
      <div class="row">
      <!-- TWITTER FEED -->
        <div class="col-xs-12">
          <div class="banner-data">
            <a class="twitter-timeline" href="https://twitter.com/nicknem92/lists/r-gionales-2015" data-widget-id="641272032743804932">Tweets de https://twitter.com/nicknem92/lists/r-gionales-2015</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
          </div>
        </div>
      </div>
    </div>
  </div>
  <span id="team"></span>
</div>

<!-- Contacts -->

<div class="home-content home-content-blue">
  <div class="title text-center">
    <h2>Equipe</h2>
  </div>

  <div class="link-back link-back-white text-center">
    <%= link_to root_path << "#accueil" do %>
      <i class="fa fa-angle-up"></i>
    <% end %>
  </div>

  <div class="container text-center">
      <div class="row">
      <!-- manu -->
        <div class="col-xs-12 col-sm-3">
          <div class="candidate-card pulsed">
            <%= image_tag 'https://avatars0.githubusercontent.com/u/13184961?v=3&s=400', class: "candidate-card" %>
            <%= link_to "https://github.com/ManuKpL", target: :_blank, class: "candidate-card-shadow" do %>
              <h5>Manu</h5>
              <p>Lead developer</p>
            <% end %>
          </div>
        </div>

        <!-- alice -->
        <div class="col-xs-12 col-sm-3">
          <div class="candidate-card pulsed">
            <%= image_tag 'https://avatars2.githubusercontent.com/u/8080784?v=3&s=400', class: "candidate-card" %>
            <%= link_to "https://github.com/alicemomo", target: :_blank, class: "candidate-card-shadow" do %>
              <h5>Alice</h5>
              <p>Lead datavizer</p>
            <% end %>
          </div>
        </div>

        <!-- vincent -->
        <div class="col-xs-12 col-sm-3">
          <div class="candidate-card pulsed">
            <%= image_tag 'https://avatars3.githubusercontent.com/u/13312958?v=3&s=400 ', class: "candidate-card" %>
            <%= link_to "https://github.com/vincentpons", target: :_blank, class: "candidate-card-shadow" do %>
              <h5>Vincent</h5>
              <p>Lead designer</p>
            <% end %>
          </div>
        </div>

        <!-- antonin -->
        <div class="col-xs-12 col-sm-3">
          <div class="candidate-card pulsed">
            <%= image_tag 'https://avatars3.githubusercontent.com/u/9062545?v=3&s=400', class: "candidate-card" %>
            <%= link_to "https://github.com/nicknem", target: :_blank, class: "candidate-card-shadow" do %>
              <h5>Antonin</h5>
              <p>Lead team-builder</p>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner text-center" id="accueil">
  <div class="banner-shadow"></div>
  <div class="banner-content-container">
    <div class="banner-content">
      <h1>Vos candidats mis à nu</h1>
      <h2>Régionales 2015 sur Twitter en Île de France</h2>
      <div class="btn-marged text-center">
        <%= link_to "Comparer les candidats", compare_path, class: "btn btn-danger" %>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-xs-4">
            <div class="banner-data">
              <%= image_tag 'white_pie.png', class:"banner-icon" %>
              <p class="hidden-xs">Analysez leurs messages</p>
            </div>
          </div>
          <div class="col-xs-4">
            <div class="banner-data">
              <%= image_tag 'white_network.png', class:"banner-icon" %>
              <p class="hidden-xs">Explorez leurs communautés</p>
            </div>
          </div>
          <div class="col-xs-4">
            <div class="banner-data">
              <%= image_tag 'white_bird.png', class:"banner-icon"%>
              <p class="hidden-xs">Evaluez leurs performances</p>
            </div>
          </div>
        </div>
      </div>
      <div class="banner-form">
        <%= simple_form_for :search, url: candidates_path, method: :get do |f| %>
          <div class="banner-form-direction">
            <div class="banner-form-marged">
              <%= f.input :name, as: :select, collection: Candidate.order(:name), label: false, prompt: "Trouver votre candidat..." %>
            </div>
            <div class="banner-form-marged">
              <%= f.button :submit, "Chercher", class: "btn btn-info" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="home-preview">
    <div class="floating">
      <p>Voir les candidats</p>
      <p><i class="fa fa-angle-double-down"></i></p>
    </div>
    <%= link_to "", "#liste-candidats", class: "home-preview-link" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <div class="title text-center">
          <p>Impact </p>
        </div>

        <div class="info text-center">
          <p>Impact is an application developed by AliceMomo, ManuKPL, VincentP and Antonin Archer</p>
          <p>Made with <i class="fa fa-heart"></i> from Paris</p>
          <p>With a little help from
          <!-- <a href="http://www.lewagon.org"> -->
            <%= image_tag("lewagon.png", width: "140") %>
          </p>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="container navbar-container">
    <%= link_to root_path, class: "navbar-item navbar-link" do %>
      <div class="navbar-header navbar-link">
        <h1>IMPACT</h1>
      </div>
    <% end %>
    <div class= "end-links">
      <%= link_to "Comparer", compare_path, class: "navbar-item navbar-link #{params['action'] == 'compare' ? 'navbar-link-red' : ''} hidden-xs" %>
      <hr class="hidden-xs">
      <%= link_to "Candidats", root_path << "#liste-candidats", class: "navbar-item navbar-link hidden-xs" %>
      <hr class="hidden-xs">
      <%= link_to "À propos", root_path << "#a-propos", class: "navbar-item navbar-link hidden-xs" %>
      <hr class="hidden-xs">
      <%= link_to "équipe", root_path << "#team", class: "navbar-item navbar-link hidden-xs" %>
      <div class="navbar-item navbar-link hidden-sm hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars" class="navbar-item navbar-link dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
            <li>
              <%= link_to "Comparer", compare_path, class: "navbar-item navbar-link #{params['action'] == 'compare' ? 'navbar-link-red' : ''}" %>
            </li>
            <li>
              <%= link_to "Candidats", root_path << "#liste-candidats", class: "navbar-item navbar-link" %>
            </li>
            <li>
              <%= link_to "À propos", root_path << "#a-propos", class: "navbar-item navbar-link" %>
            </li>
            <li>
              <%= link_to "équipe", root_path << "#team", class: "navbar-item navbar-link" %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navbar_impact.html.erb
<div id='cssmenu'>
<ul>
  <%= link_to root_path do %>
      <%= image_tag "logo2.jpg", class:"active navbar-wagon-logo" %>
    <% end %>
   <li><a href='#'>Home</a></li>
   <li class='active'><a href='#'>Candidats</a>
      <ul>
         <li><a href='#'>Analysez</a>
            <!--<ul>
               <li><a href='#'>Sub Product</a></li>
               <li><a href='#'>Sub Product</a></li>
            </ul>-->
         </li>
         <li><a href='#'>Comparez</a>
            <!--<ul>
               <li><a href='#'>Sub Product</a></li>
               <li><a href='#'>Sub Product</a></li>
            </ul>-->
         </li>
      </ul>
   </li>
   <li><a href='#'>A propos</a></li>
   <li><a href='#'>Contacts</a></li>
</ul>
</div>